blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/orgs/muxlisa-ai/discussions
    about: Ask questions and post ideas
  - name: 💭 Telegram Channel
    url: https://t.me/muxlisa_ai
    about: Ask casual questions here
